services:
    jumph_client.client_menu_listener:
        class: Jumph\Bundle\ClientBundle\EventListener\ClientMenuListener
        tags:
          - { name: kernel.event_listener, event: jumph.build_menu, method: onMenuClient }
