Jumph\Bundle\ClientBundle\Entity\Company:
    type: entity
    table: jumph_company

    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: true

    oneToMany:
        employees:
            targetEntity: Employee
            mappedBy: company
            cascade: ["persist", "remove"]
        projects:
            targetEntity: \Jumph\Bundle\ProjectBundle\Entity\Project
            mappedBy: company

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
            length: 150
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
