imports:
    - { resource: config.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: info

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db

liip_functional_test:
    cache_sqlite_db: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: plaintext

    firewalls:
        main:
            http_basic: ~
