jumph_installer:
    resource: "@JumphInstallerBundle/Resources/config/routing.yml"
    prefix:   /

jumph_calendar:
    resource: "@JumphCalendarBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

jumph_client:
    resource: "@JumphClientBundle/Resources/config/routing.yml"
    prefix:   /

jumph_app:
    resource: "@JumphAppBundle/Resources/config/routing.yml"
    prefix:   /

jumph_dashboard:
    resource: "@JumphDashboardBundle/Resources/config/routing.yml"
    prefix:   /

jumph_user:
    resource: "@JumphUserBundle/Resources/config/routing.yml"
    prefix:   /

jumph_quotation:
    resource: "@JumphQuotationBundle/Resources/config/routing.yml"
    prefix:   /

jumph_email:
    resource: "@JumphEmailBundle/Resources/config/routing.yml"
    prefix:   /

jumph_project:
    resource: "@JumphProjectBundle/Resources/config/routing.yml"
    prefix:   /

jumph_time_tracker:
    resource: "@JumphTimeTrackerBundle/Resources/config/routing.yml"
    prefix:   /

jumph_issue:
    resource: "@JumphIssueBundle/Resources/config/routing.yml"
    prefix:   /

