Jumph\Bundle\ProjectBundle\Entity\ProjectStatus:
    type: entity
    table: jumph_project_status

    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: true

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
            length: 150
        description:
            type: text
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
